# Generated by Django 4.0 on 2022-02-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='date',
            field=models.DateField(default='none'),
        ),
        migrations.AddField(
            model_name='contact_us',
            name='time',
            field=models.TimeField(default='none'),
        ),
    ]
