# Generated by Django 4.0 on 2022-02-09 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_contact_us_date_alter_contact_us_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
