# Generated by Django 4.0 on 2022-02-09 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_contact_us_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
