# Generated by Django 4.0 on 2022-02-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_contact_us_date_remove_contact_us_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='dates',
            field=models.DateField(default=None),
        ),
    ]
